sudo : required
services:
    - docker


before_install:
    - docker build -t hamzaudaipur/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hamzaudaipur/docker-react npm run test -- --coverage